### PR TITLE
prepare package creation

### LINKED ISSUE #6: No package available
Hi

Thanks for your cool script. It's exactly what I need for my personal project. Do you have any plans about releasing the package on [npmjs](https://npmjs.com)?

It would really simplify development and deployment.

Thanks in advance

Michael

### PR DESCRIPTION
**Pull request by mblaettler**
To have the crossword generator available in bigger javascript projects it is helpful to add it to npmjs. This commit rewrites the code and adds files required for uploading and installing a package via npm.
**CAUCTION**: This commit will break the index.html. It is required to use unpkg unce the node package is deployed.

Fixes #6

### CODE REVIEW

**Comment by mblaettler** [comment]
Hi @MichaelWehar 

Like discussed in #6 I prepared everything for the package to be released on [npmjs](https://npmjs.com).

The following steps are required to publish it:

1. Create a free account on [npmjs](https://npmjs.com)
2. Make sure you have installed `npm`. If not, follow [this guide](https://www.npmjs.com/get-npm) to install it.
3. Run `npm login` and authenticate yourself with the login created in step 1.
4. Check the `package.json` and change any fields you'd like (if you change anything run `npm install` afterwards to generate a new lock file)
5. Run `npm publish` to publish the package on npmjs.

In case you have any troubles, feel free to contact me.

**Comment by MichaelWehar** [comment]
Woo hoo!!  Thank you so much for doing this!  :)

I'm sorry, I've been a bit busy finishing things up with final grading for the semester.

I'm hoping that I'll be able to review this in a couple days.

I hope that you have a Happy Holidays!

**Comment by mblaettler** [comment]
No hurry. I'm also quite busy due to the end of the semester and paused my project.

Enjoy your holidays!

**Comment by MichaelWehar** [comment]
Thank you again so much for doing this!

I am going to merge this into a branch called npm.

Next, I'm going to make some minor changes.

Then, I will give you an update and publish it to npm.  :)

Hope that you have a Happy New Year!

**Pull request merged**
